CREATE TABLE IF NOT EXISTS LIKED_MOVIES (
    ID UUID NOT NULL,
    MOVIE_ID UUID,
    USER_ID UUID,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MOVIES (
    ID UUID NOT NULL,
    DOMAIN_TYPE VARCHAR(255),
    LANGUAGE VARCHAR(255),
    LENGTH INT4 NOT NULL,
    NAME VARCHAR(255),
    RELEASE_DATE DATE,
    USER_ID UUID,
    SUMMARY VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    ID UUID NOT NULL,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    PRIMARY KEY (ID)
);

ALTER TABLE MOVIES DROP CONSTRAINT IF EXISTS FK_USER;
ALTER TABLE MOVIES ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS;